[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short -n auto
retries = 2
retry_delay = 2
markers =
    slow: Slow running tests that should not be run by default.
    integration: Integration tests involving external systems or services.
    login: test for login.
    items: test for items.
    # command for run:  pytest -m slow
